[package]
name = "rtiw-rs"
version = "0.1.0"
authors = ["eric556 <enpie123@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minifb = "0.17"
cgmath = "0.17"